# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f7f57e89c2934d8c295abcd1b5a84166b2f00aa124ef1708cbc30b526e5153458daf8b01b19f8f92845f93f4c4abba6a35b0a42ecd5c27b34081af6de54d7b5

test:
  secret_key_base: 24b4c2f5be2f1cda89237f5b5701ec271e1fc68f8d5fd0204a1ec52c0f96dacd2a4910484f3f7d79b7cc81dcdb0b3522e1fb2a2faa372bd2492c42010fa1026c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
